volumes:
  data1:
  data2:
  data3:

networks:
  blockchain_network:
    driver: bridge

services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: python-blockchain-backend
    environment:
      FLASK_RUN_PORT: 8000
      DATA_FILE: /data/chain.json
    networks:
      - blockchain_network      
    ports:
      - 8000:8000
    volumes:
      - "/home/docker/data/python/data1:/data"
  backend2:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: python-blockchain-backend
    environment:
      FLASK_RUN_PORT: 8001
      DATA_FILE: /data/chain.json
    networks:
      - blockchain_network      
    ports:
      - 8001:8001
    volumes:
      - "/home/docker/data/python/data2:/data"
  backend3:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: python-blockchain-backend
    environment:
      FLASK_RUN_PORT: 8002
      DATA_FILE: /data/chain.json
    networks:
      - blockchain_network      
    ports:
      - 8002:8002
    volumes:
      - "/home/docker/data/python/data3:/data"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: python-blockchain-frontend
    environment:
      FLASK_RUN_PORT: 5000
    networks:
      - blockchain_network      
    ports:
      - 5000:5000