FROM python:3.11

RUN mkdir /app
COPY . /app
WORKDIR /app
RUN python -m pip install -r requirements.txt
ENV FLASK_RUN_SERVER_NAME=0.0.0.0
EXPOSE 5000
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
#ENTRYPOINT [ "python", "run_app.py" ]

